### ISSUE TITLE
Issues in directories with spaces

### ISSUE THREAD

**Issue by bpato** [vv221/play.it#1]
I tried run the scripts for shadowrun dragonfall and the witcher game from gog in folders whose name had spaces.

first, the script did not finished.
>...
>Looking for target files…
>Using /home/brais/Descargas/b a c/gog_shadowrun_dragonfall_director_s_cut_2.6.0.11.sh
>
> Building package directories…
> Extracting data from gog_shadowrun_dragonfall_director_s_cut_2.6.0.11.sh…
>This might take several minutes.
>Fixing file rights…
>find: «/home/brais/Descargas/b»: No existe el archivo o el directorio

second, the script finished but did not set the value for the size in the write_pkg_debian method
>...
>Looking for target files…
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12.exe
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-1.bin
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-2.bin
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-3.bin
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-4.bin
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-5.bin
>Using /home/brais/Descargas/a b c/setup_the_witcher_enhanced_edition_2.0.0.12-6.bin
>
>Building package directories…
>This might take several minutes.
>Extracting data from setup_the_witcher_enhanced_edition_2.0.0.12.exe…
>Extracting icons from witcher.exe…
>Done.
>
>Writing launcher script for The Witcher…
>Writing menu entry for The Witcher…
>
>Building packages…
>This might take several minutes.
>realpath: 'c/the-witcher_1.5.726-gog2.0.0.12_i386/*': No existe el archivo o el directorio
>du: no se puede acceder a '/home/brais/Descargas/a': No existe el archivo o el directorio
>du: no se puede acceder a '/home/brais/Descargas/a': No existe el archivo o el directorio
>du: no se puede acceder a 'b': No existe el archivo o el directorio
>du: no se puede acceder a 'c/b': No existe el archivo o el directorio
>Writing package meta-data for The Witcher: Enhanced Edition…
>realpath: 'c/the-witcher-data_1.5.726-gog2.0.0.12_i386/*': No existe el archivo o el directorio
>du: no se puede acceder a '/home/brais/Descargas/a': No existe el archivo o el directorio
>du: no se puede acceder a '/home/brais/Descargas/a': No existe el archivo o el directorio
>du: no se puede acceder a 'b': No existe el archivo o el directorio
>du: no se puede acceder a 'c/b': No existe el archivo o el directorio
>...

**Comment by vv221** [comment]
Thank you for the report!

Both issues should be fixed with commits 4c0564f and e9476dd.
I will close this issue when they are merged into master and a fixed version of the library is downloadable from the project website.

**Comment by vv221** [comment]
The fixes have been merged into master and can be downloaded from ./play.it website.
