### ISSUE TITLE
Full game path

### ISSUE THREAD

**Issue by hadogenes** [vv221/play.it#11]
https://github.com/vv221/play.it/blob/d441f2d7164814bb39241473e7233bcae3b6657d/play.it-2/src/30_launchers.sh#L339

I think there should be full game path, because if I use prefix _/opt/games/<game-name>_ this don't work

**Comment by vv221** [comment]
You’re right, a fix should be part of the next library update.

**Comment by vv221** [comment]
Fixed in release 2.3.1:
https://github.com/vv221/play.it/releases/tag/2.3.1
