### ISSUE TITLE
Dungeon Keeper II software acceleration support

### ISSUE THREAD

**Issue by rtentser** [vv221/play.it#13]
There is the bug on my system: https://bugs.winehq.org/show_bug.cgi?id=44260. So i want to use DKII_SOFT.EXE instead of DKII-DX.EXE. It works fine when i use it with wine-2.0.3 without your script.

But here's the thing. I tried to change GAME_EXE variable in dungeon-keeper-2 script and it didn't work (it works with dxii.EXE). The game just finish its work without even starting. And i don't know how to fix the script to make it work with dkii_soft.exe.

I think it'll be good to have software acceleration support in your script. Something like alternative starting script with dkii_soft.exe.

**Comment by vv221** [comment]
You’re right, I’m going to work on it so you can chose either software or hardware acceleration on game launch.

**Comment by vv221** [comment]
This is fixed with commit 5c1735ab6ac43edc4cbd33a6662cfcc17e149c95, please try again with the new script:
https://wiki.dotslashplay.it/en/games/dungeon-keeper-2

**Comment by rtentser** [comment]
I tried it. And it works! Thank you, man.
