### ISSUE TITLE
Start morrowind with the launcher

### ISSUE THREAD

**Issue by rtentser** [vv221/play.it#14]
Now the script uses morrowind.exe to start the game.
But the original game starts with "morrowind launcher.exe" because it let to choose a plugins.
I think the script should use the launcher too.

**Comment by vv221** [comment]
I’ve been modding my game through configuration files for so long that I forgot the launcher can be used for that ;)
I will make the script start the launcher on the next update.

**Comment by vv221** [comment]
This change is included in commit 27054adf65c6ab467e59872d9ca4eac2c3873825
I’ll close this issue once it’s merged into master.

**Comment by vv221** [comment]
The new script for Morrowind is part of release 2.4.2
