### ISSUE TITLE
Baldur's Gate Enchanced Edition

### ISSUE THREAD

**Issue by rtentser** [vv221/play.it#16]
The game fails to start, i get an error:
./BaldursGate: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

libssl_1.0.0_32-bit.tar.gz is in the directory when i build a package.
libssl1.0.2 was installed from debian repository.

**Comment by vv221** [comment]
Looks like a bug on our side, I’ll check the building process and report back here.

**Comment by vv221** [comment]
Bug confirmed, I’m working on a fix.

**Comment by vv221** [comment]
This is fixed in commit 577279209efbc88739aff0f50ebf917ce2cccd31

**Comment by rtentser** [comment]
I tried new script. Same bug.

**Comment by vv221** [comment]
You might need to delete the corrupted prefix generated by the previous script:
```
rm -Rf ~/.local/share/play.it/prefixes/baldurs-gate-enhanced-edition
```
Then just run the game again, no need to re-install it.
