### ISSUE TITLE
Allow RPM export

### ISSUE THREAD

**Issue by StraToN** [vv221/play.it#18]
Hello !
Thanks for this project. I am currently giving it a try, looking for differences between this and PlayOnLinux.

I am using Mageia 6 which uses RPM as packet manager. ./play.it does not export to RPM yet. Even though it is possible to export to DEB and convert to RPM with alien, direct export to RPM would save a bit of time. So I am creating an issue according it :)

**Comment by vv221** [comment]
RPM is the next in line of supported packages formats, be we don’t have any RPM-based distribution user in the active contributors yet.
If you can point me to some good documentation on the package format I can begin the work, but I will need help to test the resulting packages. And if you feel like working on it, be it on yourself or together with me, please don’t hesitate to ping me on IRC when you have some free time ;)

**Comment by StraToN** [comment]
I work on a Mageia 6 distribution.
I'd be pleased to test RPMs. I advise you to choose one game that we both own so we can test :)

**Comment by vv221** [comment]
I think I’ll start with a free demo from GOG.com, do you have an account there?

**Comment by StraToN** [comment]
Sure! I just invited you.

**Comment by vv221** [comment]
The discussion about RPM packages should migrate to Framagit, where we try to centralize everything about ./play.it : https://framagit.org/vv221/play.it/issues/3

Registration on Framagit is free, it is based on Free software, and is maintained by nice people ;)
